---
title: "my_vignette"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{my_vignette}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(lab6)
# make preparation for future calculation
RNGversion(min(as.character(getRversion()),"3.5.3"))
set.seed(42, kind = "Mersenne-Twister", normal.kind = "Inversion")
n <- 2000
knapsack_objects <-
  data.frame(
    w=sample(1:4000, size = n, replace = TRUE),
    v=runif(n = n, 0, 10000)
  )

```



```{r}
timestart<-Sys.time()

brute_force_knapsack(x = knapsack_objects[1:16,], W = 3500,parallel = FALSE)

timeend<-Sys.time()
runningtime<-timeend-timestart
print(runningtime)
```



```{r}
timestart<-Sys.time()

brute_force_knapsack(x = knapsack_objects[1:16,], W = 3500,parallel = TRUE)

timeend<-Sys.time()
runningtime<-timeend-timestart
print(runningtime)
```


```{r}
timestart<-Sys.time()

greedy_knapsack(x = knapsack_objects[1:16,], W = 3500)

timeend<-Sys.time()
runningtime<-timeend-timestart
print(runningtime)
```


```{r}
timestart<-Sys.time()

knapsack_dynamic(x = knapsack_objects[1:16,], W = 3500)

timeend<-Sys.time()
runningtime<-timeend-timestart
print(runningtime)
```













